.TH "stack.c" 3 "16 Sep 2003" "Sample" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stack.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stack.h'\fP
.br
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpush\fP (\fBstack\fP s, int val)"
.br
.RI "\fIThis function is used to push stuff.\fP"
.ti -1c
.RI "int \fBpop\fP (\fBstack\fP s, int val)"
.br
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
.PP
.PP
Definition in file \fBstack.c\fP.
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "int pop (\fBstack\fP s, int val)"
.PP
\fBTodo: \fP
.in +1c
 Impliment this function  
.PP
\fBExamples: \fP
.in +1c
\fBstack_example.c\fP.
.PP
Definition at line 24 of file stack.c.
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Sample from the source code.
