.TH "own" 3 "16 Sep 2003" "Sample" \" -*- nroff -*-
.ad l
.nh
.SH NAME
own \- Your own documentation
.PP
You just need to start putting these structured comments in your .h files and things will be good.
.PP
.SH "Step 1: making .h files"
.PP 
.SS "Type stuff"
.PP
First, type some stuff
.PP
.SS "Add documentation"
.PP
Then add documentation.
.PP
.SS "Compile."
.PP
Then compile
.PP

