foldersTree = gFld("<b>Sample</b>", "", "")
     insDoc(foldersTree, gLnk("Sample documentation example", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("documentation.h", "", ""))
       insDoc(aux1, gLnk("stack.c", "", "stack_8c.html"))
       insDoc(aux1, gLnk("stack.h", "", "stack_8h.html"))
aux1 = insFld(foldersTree, gFld("Data Structures", "", "annotated.html"))
       insDoc(aux1, gLnk("stack", "", "structstack.html"))
     insDoc(foldersTree, gLnk("Data Fields", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Modules", "", "modules.html"))
       insDoc(aux1, gLnk("Stack", "", "group__stack.html"))
aux1 = insFld(foldersTree, gFld("Examples", "", "examples.html"))
       insDoc(aux1, gLnk("stack_example.c", "", "stack__example_8c-example.html"))
     insDoc(foldersTree, gLnk("Globals", "", "globals.html"))
aux1 = insFld(foldersTree, gFld("Related Pages", "", "pages.html"))
       insDoc(aux1, gLnk("Your own documentation", "", "own.html"))
       insDoc(aux1, gLnk("Todo List", "", "todo.html"))
       insDoc(aux1, gLnk("Deprecated List", "", "deprecated.html"))
       insDoc(aux1, gLnk("Bug List", "", "bug.html"))
